### ISSUE TITLE
npm run build-assets error

### ISSUE THREAD

**Issue by saqibkhan2523** [mirumee/saleor#2545]
```
saleor@0.0.0 build-assets /var/www/glintwear.com/public_html/ecomtest2/saleor
> webpack -p --progress

  0% compiling(node:26094) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead                                    Hash: 88247e9b654e9dfbcc89
Version: webpack 4.16.5
Time: 219ms
Built at: 08/09/2018 6:52:46 PM
 3 assets
[0] ./saleor/static/dashboard/js/dashboard.js 2.98 KiB {0} [built] [failed] [1 error]
[1] ./saleor/static/dashboard/js/document.js 2.98 KiB {1} [built] [failed] [1 error]
[2] ./saleor/static/js/storefront.js 3.1 KiB {2} [built] [failed] [1 error]

ERROR in ./saleor/static/js/storefront.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module '@babel/preset-es2015' from '/var/www/glintwear.com/public_html/ecomtest2/saleor'
    at Function.module.exports [as sync] (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/resolve/lib/sync.js:43:15)
    at resolveStandardizedName (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/@babel/core/lib/config/files/plugins.js:101:31)
    at resolvePreset (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/@babel/core/lib/config/files/plugins.js:58:10)
    at loadPreset (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/@babel/core/lib/config/files/plugins.js:77:20)
    at createDescriptor (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/@babel/core/lib/config/config-descriptors.js:114:9)
    at items.map (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/@babel/core/lib/config/config-descriptors.js:69:50)
    at Array.map (<anonymous>)
    at createDescriptors (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/@babel/core/lib/config/config-descriptors.js:69:29)
    at createPresetDescriptors (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/@babel/core/lib/config/config-descriptors.js:61:10)
    at presets (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/@babel/core/lib/config/config-descriptors.js:43:19)
    at mergeChainOpts (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/@babel/core/lib/config/config-chain.js:303:26)
    at /var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/@babel/core/lib/config/config-chain.js:266:7
    at buildRootChain (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/@babel/core/lib/config/config-chain.js:106:22)
    at loadPrivatePartialConfig (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/@babel/core/lib/config/partial.js:55:55)
    at Object.loadPartialConfig (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/@babel/core/lib/config/partial.js:80:18)
    at Object.<anonymous> (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/babel-loader/lib/index.js:82:26)
    at Generator.next (<anonymous>)
    at step (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/babel-loader/lib/index.js:3:221)
    at _next (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/babel-loader/lib/index.js:3:409)
    at /var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/babel-loader/lib/index.js:3:477
    at new Promise (<anonymous>)
    at Object.<anonymous> (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/babel-loader/lib/index.js:3:97)
    at Object._loader (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/babel-loader/lib/index.js:148:18)
    at Object.loader (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/babel-loader/lib/index.js:36:18)
    at Object.<anonymous> (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/babel-loader/lib/index.js:31:12)

ERROR in ./saleor/static/dashboard/js/dashboard.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module '@babel/preset-es2015' from '/var/www/glintwear.com/public_html/ecomtest2/saleor'
    at Function.module.exports [as sync] (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/resolve/lib/sync.js:43:15)
    at resolveStandardizedName (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/@babel/core/lib/config/files/plugins.js:101:31)
    at resolvePreset (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/@babel/core/lib/config/files/plugins.js:58:10)
    at loadPreset (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/@babel/core/lib/config/files/plugins.js:77:20)
    at createDescriptor (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/@babel/core/lib/config/config-descriptors.js:114:9)
    at items.map (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/@babel/core/lib/config/config-descriptors.js:69:50)
    at Array.map (<anonymous>)
    at createDescriptors (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/@babel/core/lib/config/config-descriptors.js:69:29)
    at createPresetDescriptors (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/@babel/core/lib/config/config-descriptors.js:61:10)
    at presets (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/@babel/core/lib/config/config-descriptors.js:43:19)
    at mergeChainOpts (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/@babel/core/lib/config/config-chain.js:303:26)
    at /var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/@babel/core/lib/config/config-chain.js:266:7
    at buildRootChain (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/@babel/core/lib/config/config-chain.js:106:22)
    at loadPrivatePartialConfig (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/@babel/core/lib/config/partial.js:55:55)
    at Object.loadPartialConfig (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/@babel/core/lib/config/partial.js:80:18)
    at Object.<anonymous> (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/babel-loader/lib/index.js:82:26)
    at Generator.next (<anonymous>)
    at step (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/babel-loader/lib/index.js:3:221)
    at _next (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/babel-loader/lib/index.js:3:409)
    at /var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/babel-loader/lib/index.js:3:477
    at new Promise (<anonymous>)
    at Object.<anonymous> (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/babel-loader/lib/index.js:3:97)
    at Object.loader (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/babel-loader/lib/index.js:36:18)
    at Object.<anonymous> (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/babel-loader/lib/index.js:31:12)

ERROR in ./saleor/static/dashboard/js/document.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module '@babel/preset-es2015' from '/var/www/glintwear.com/public_html/ecomtest2/saleor'
    at Function.module.exports [as sync] (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/resolve/lib/sync.js:43:15)
    at resolveStandardizedName (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/@babel/core/lib/config/files/plugins.js:101:31)
    at resolvePreset (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/@babel/core/lib/config/files/plugins.js:58:10)
    at loadPreset (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/@babel/core/lib/config/files/plugins.js:77:20)
    at createDescriptor (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/@babel/core/lib/config/config-descriptors.js:114:9)
    at items.map (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/@babel/core/lib/config/config-descriptors.js:69:50)
    at Array.map (<anonymous>)
    at createDescriptors (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/@babel/core/lib/config/config-descriptors.js:69:29)
    at createPresetDescriptors (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/@babel/core/lib/config/config-descriptors.js:61:10)
    at presets (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/@babel/core/lib/config/config-descriptors.js:43:19)
    at mergeChainOpts (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/@babel/core/lib/config/config-chain.js:303:26)
    at /var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/@babel/core/lib/config/config-chain.js:266:7
    at buildRootChain (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/@babel/core/lib/config/config-chain.js:106:22)
    at loadPrivatePartialConfig (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/@babel/core/lib/config/partial.js:55:55)
    at Object.loadPartialConfig (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/@babel/core/lib/config/partial.js:80:18)
    at Object.<anonymous> (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/babel-loader/lib/index.js:82:26)
    at Generator.next (<anonymous>)
    at step (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/babel-loader/lib/index.js:3:221)
    at _next (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/babel-loader/lib/index.js:3:409)
    at /var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/babel-loader/lib/index.js:3:477
    at new Promise (<anonymous>)
    at Object.<anonymous> (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/babel-loader/lib/index.js:3:97)
    at Object.loader (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/babel-loader/lib/index.js:36:18)
    at Object.<anonymous> (/var/www/glintwear.com/public_html/ecomtest2/saleor/node_modules/babel-loader/lib/index.js:31:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! saleor@0.0.0 build-assets: `webpack -p --progress`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the saleor@0.0.0 build-assets script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2018-08-09T18_52_46_139Z-debug.log
```

I am getting this error eventhough I am using nodejs 10.8.0. and i guess its because of this I am getting error:
```
ModuleBuildError in 
            Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module '@babel/preset-es2015' from '/var/www/glintwear.com/public_html/ecomtest2/saleor'
```
after I run server and try to open saleor

**Comment by NyanKiyoshi** [comment]
This may be a dumb question but did you try to run `npm i` before to update any outdated dependency?

**Comment by saqibkhan2523** [comment]
yes I ran it but its still giving error on build-assets

**Comment by patrys** [comment]
Does `npm install` return any errors?

**Comment by saqibkhan2523** [comment]
No errors just two warnings

**Comment by asalt** [comment]
@saqibkhan2523 were you able to resolve this? I have what sounds like the same problem (`npm install` giving warnings and `build-assets` 3 builds failing)

**Comment by saqibkhan2523** [comment]
yes @asalt  update your node to latest stable version 10.x then re run `npm install` and `npm run build-assets` commands

**Comment by asalt** [comment]
Thanks - upgrading to 10.x version did it for me.

Note after I ran `npm install` I ran `npm audit fix` which prevented `npm run build-assets` from working. By not running `npm audit fix` I was able to get everything working

**Comment by aventurella** [comment]
I'm getting the same issue.

It won't even build with `webpack-cli 2.1.5` So I bump that to `3.1.2` then it tries to build, but it throws the error above.

```
node: v10.11.0
webpack: 4.20.2
webpack-cli: 3.1.2
typescript: 3.1.1
```

Also when I blow away `node_modules` and try my hand at it again from a clean slate I sometimes get error like this:

```
ERROR in [at-loader] ./dashboard-next/AppRoot.tsx:283:34
    TS2339: Property 'menuListItemText' does not exist on type 'Record<never, string>'.

ERROR in [at-loader] ./dashboard-next/orders/components/OrderCustomerEditDialog/OrderCustomerEditDialog.tsx:70:43
    TS2339: Property 'root' does not exist on type 'Record<never, string>'.

ERROR in [at-loader] ./dashboard-next/queries.tsx:15:9
    TS2322: Type 'typeof Query' is not assignable to type 'ComponentType<QueryProps<TData, TVariables>>'.
  Type 'typeof Query' is not assignable to type 'ComponentClass<QueryProps<TData, TVariables>, any>'.
    Types of property 'propTypes' are incompatible.
      Type '{ client: Requireable<object>; children: Validator<(...args: any[]) => any>; fetchPolicy: Requireable<string>; notifyOnNetworkStatusChange: Requireable<boolean>; onCompleted: Requireable<(...args: any[]) => any>; ... 5 more ...; partialRefetch: Requireable<...>; }' is not assignable to type 'ValidationMap<QueryProps<TData, TVariables>>'.
        Property 'errorPolicy' is missing in type '{ client: Requireable<object>; children: Validator<(...args: any[]) => any>; fetchPolicy: Requireable<string>; notifyOnNetworkStatusChange: Requireable<boolean>; onCompleted: Requireable<(...args: any[]) => any>; ... 5 more ...; partialRefetch: Requireable<...>; }'.

```

**Comment by adonig** [comment]
I ran into those problems when trying to use yarn instead of npm. When using npm with node@10 everything works as expected.
