### ISSUE TITLE
Does Saleor work with Django 1.8?

### ISSUE THREAD

**Issue by chadsaun** [mirumee/saleor#302]
I just upgraded and got this error. Looks like Django [removed this in 1.8](https://github.com/django/django/commit/80facd7a0f3e545d800ad759ce5458f5f2bc246e)?

    File "/Users/chad/site/rbi-com-saleor/server/saleor/core/utils/__init__.py", line 7, in <module>
        from django.http.request import absolute_http_url_re
    ImportError: cannot import name absolute_http_url_re

Has anyone got Saleor to work with Django 1.8?

**Comment by patrys** [comment]
We run with 1.8.1 on a daily basis. If you look at [the file in question](https://github.com/mirumee/saleor/blob/master/saleor/core/utils/__init__.py), there is no such import.

**Comment by chadsaun** [comment]
Oh ok, sorry.  Looks like this was added by us then.  Thanks!
